version: "3.9"

services:

  db:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hub_insight
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/


  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
    postgres-data:
    redis-data:

