version: "3.9"

services:

  db:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hub_insight
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/


  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


  rabbitmq:
    image: "rabbitmq:alpine"
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672


volumes:
    postgres-data:
    redis-data:

