version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hub_insight
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  celery:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    # command: celery -A hub_insight.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    container_name: worker
    command: ./docker/celery_entrypoint.sh
    environment:
      - DATABASE_URL=psql://user:password@db:5432/hub_insight
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  beats:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    # command: celery -A hub_insight.tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    container_name: beats
    command: ./docker/beats_entrypoint.sh
    environment:
      - DATABASE_URL=psql://user:password@db:5432/hub_insight
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
