# Generated by Django 4.0.7 on 2025-10-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='script_filename',
            field=models.CharField(default='test.py', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='version',
            field=models.CharField(default='v1', max_length=255),
        ),
    ]
