# Generated by Django 4.0.7 on 2025-10-21 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_script_filename_job_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('var_type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float')], max_length=25)),
                ('default', models.CharField(default=None, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
