# Generated by Django 4.0.7 on 2025-10-21 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='var_type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float'), ("{<class 'int'>: ('int', 'Integer'), <class 'str'>: ('str', 'String'), <class 'bool'>: ('bool', 'Boolean'), <class 'float'>: ('float', 'Float')}", 'Map Python Var')], max_length=255),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float'), ("{<class 'int'>: ('int', 'Integer'), <class 'str'>: ('str', 'String'), <class 'bool'>: ('bool', 'Boolean'), <class 'float'>: ('float', 'Float')}", 'Map Python Var')], max_length=255)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_type', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
