# Generated by Django 4.0.7 on 2025-10-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_variable_var_type_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float')], max_length=255),
        ),
        migrations.AlterField(
            model_name='variable',
            name='var_type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float')], max_length=255),
        ),
    ]
