# Generated by Django 4.0.7 on 2025-10-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_response_response_type_alter_variable_var_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='response_type',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float')], default='str', max_length=255),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
