# Generated by Django 4.0.7 on 2025-10-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_scheduletask_delete_customizeperiodictask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduletask',
            old_name='enable',
            new_name='enabled',
        ),
    ]
