# Generated by Django 4.0.7 on 2025-10-23 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_logtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtask',
            name='job_version',
            field=models.CharField(default='v1', max_length=255),
        ),
        migrations.AlterField(
            model_name='logtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.task'),
        ),
    ]
