# Generated by Django 4.0.7 on 2025-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_logtask_job_version_alter_logtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtask',
            name='error_message',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
