# Generated by Django 4.0.7 on 2025-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_logtask_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
