# Generated by Django 4.0.7 on 2025-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logtask',
            index=models.Index(fields=['task', 'created_at'], name='tasks_logta_task_id_83b21d_idx'),
        ),
        migrations.AddIndex(
            model_name='logtask',
            index=models.Index(fields=['is_ok'], name='tasks_logta_is_ok_7447c0_idx'),
        ),
    ]
