# Generated by Django 4.0.7 on 2025-10-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_logtask_tasks_logta_task_id_83b21d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='celery_cron_schedule',
        ),
    ]
