# Generated by Django 4.0.7 on 2025-10-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_celery_cron_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tasks.task'),
        ),
    ]
