# Generated by Django 4.0.7 on 2025-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtask',
            name='response_value',
            field=models.TextField(default=None, null=True),
        ),
    ]
