# Generated by Django 4.0.7 on 2025-10-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_logtask_response_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logtask',
            options={'ordering': ['-created_at']},
        ),
    ]
